CREATE TABLE Instrument (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Trade (
    Id SERIAL PRIMARY KEY,
    InstrumentId INTEGER NOT NULL REFERENCES Instrument(Id),
    DateEn TIMESTAMP WITH TIME ZONE NOT NULL,
    Open DECIMAL NOT NULL,
    High DECIMAL NOT NULL,
    Low DECIMAL NOT NULL,
    Close DECIMAL NOT NULL
);